### ISSUE TITLE
feat: adopt pre-created EIPs with specific tags

### ISSUE THREAD

**Issue by lukasmrtvy** [quortex/kubestatic#144]
Hi,
I would like to see support for adopting already created EIPs via EIP tags

```
apiVersion: kubestatic.quortex.io/v1alpha1
kind: ExternalIP
metadata:
  name: externalip-sample
spec:
  nodeName: ip-10-231-6-214.eu-west-1.compute.internal
  eipTags:
     team: red
     env: staging
```

and

```
kubestatic.quortex.io/externalip-auto-assign: true
kubestatic.quortex.io/externalip-auto-assign-tags: "team=red,env=staging"
```
