### ISSUE TITLE
feat: nodeSelector instead of nodeName

### ISSUE THREAD

**Issue by lukasmrtvy** [quortex/kubestatic#148]
Hi, it would be superb to support node selector instead of nodeName, which is quite limiting in case of multiple nodes spun via ASG for example.

For example:
```
apiVersion: kubestatic.quortex.io/v1alpha1
kind: ExternalIP
metadata:
  name: externalip-sample
spec:
  selector: 
     matchLabels: 
         egress: true
```

Thanks
